# This is a basic workflow to help you get started with Actions

name: demo-gha-pipeline

on:
  workflow_dispatch:
   inputs:
     action:
        type: choice
        description: python code build
        options:
        - devl
        - prod

jobs:
  pyhon-devl:
    runs-on: ubuntu-latest
    if: ${{ github.events.inputs.action == 'devl' }}
    environment: Developement
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64' 
      - run: python3 demo.py
        
  pyhon-prod:
    runs-on: ubuntu-latest
    environment: Production
    if: ${{ github.events.inputs.action == 'prod' }}
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64' 
      - run: python3 demo.py
    needs: pyhon-devl
 
