# This is a basic workflow to help you get started with Actions

name: demo-gha-pipeline

on:
  workflow_dispatch:

jobs:
  build-devl:
    runs-on: ubuntu-latest
    environment: Developement
    steps:
      - uses: actions/checkout@v3
      - name: echo build 
        run: echo run build devl
        
  test-devl:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'test' }}
    environment: Developement
    steps:
      - name: echo test
        run: echo run test devl
    needs: build-devl
   
  
  deploy-devl:
    runs-on: ubuntu-latest
    environment: Developement
    steps:
      - name: echo deploy
        run: echo run deploy devl
    needs: test-devl
  
  build-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - name: echo build 
        run: echo run build prod
        
  test-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: echo test
        run: echo run test prod
    needs: build-prod
   
  deploy-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: echo deploy
        run: echo run deploy prod
    needs: test-prod
    

