name: demo-gha-pipeline

on:
  workflow_dispatch:
    inputs:
        action:
          type: choice
          description: action to take
          options: 
          - devl
          - prod
env:
  Name: Demo

jobs:
  python-devl-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'devl' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: |
          echo "$Name"
          python3 --version
          python3 demo.py

   
  python-prod-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'prod' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64' 
      - run: |
          python3 --version
          python3 demo.py
