# This is a basic workflow to help you get started with Actions

name: demo-gha-pipeline

on:
  workflow_dispatch:

jobs:
  get-secret-devl:
    runs-on: ubuntu-latest
    environment: Developement
    steps:
      - uses: actions/checkout@v3
      - name: echo get secret devl  
        run: |
          echo ${{ secrets.USERNAME }}
          echo ${{ secrets.PASSWORD }}
        
  get-secret-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: echo get secret prod 
        run: |
          echo ${{ secrets.USERNAME }}
          echo ${{ secrets.PASSWORD }}
 
